// Generated by verif/models/palette5242.py from MAME's resistor weights.
// 5-bit channel value -> 8-bit output: normal, shadow (effects bank,
// palette bit 15 clear) and hilight (effects bank, bit 15 set).
function automatic [7:0] pal_normal(input [4:0] v);
    case (v)
        5'd0: pal_normal = 8'd0;
        5'd1: pal_normal = 8'd8;
        5'd2: pal_normal = 8'd16;
        5'd3: pal_normal = 8'd25;
        5'd4: pal_normal = 8'd33;
        5'd5: pal_normal = 8'd41;
        5'd6: pal_normal = 8'd49;
        5'd7: pal_normal = 8'd58;
        5'd8: pal_normal = 8'd66;
        5'd9: pal_normal = 8'd74;
        5'd10: pal_normal = 8'd82;
        5'd11: pal_normal = 8'd91;
        5'd12: pal_normal = 8'd99;
        5'd13: pal_normal = 8'd107;
        5'd14: pal_normal = 8'd115;
        5'd15: pal_normal = 8'd123;
        5'd16: pal_normal = 8'd132;
        5'd17: pal_normal = 8'd140;
        5'd18: pal_normal = 8'd148;
        5'd19: pal_normal = 8'd156;
        5'd20: pal_normal = 8'd164;
        5'd21: pal_normal = 8'd173;
        5'd22: pal_normal = 8'd181;
        5'd23: pal_normal = 8'd189;
        5'd24: pal_normal = 8'd197;
        5'd25: pal_normal = 8'd206;
        5'd26: pal_normal = 8'd214;
        5'd27: pal_normal = 8'd222;
        5'd28: pal_normal = 8'd230;
        5'd29: pal_normal = 8'd239;
        5'd30: pal_normal = 8'd247;
        5'd31: pal_normal = 8'd255;
        default: pal_normal = 8'd0;
    endcase
endfunction
function automatic [7:0] pal_shadow(input [4:0] v);
    case (v)
        5'd0: pal_shadow = 8'd0;
        5'd1: pal_shadow = 8'd7;
        5'd2: pal_shadow = 8'd13;
        5'd3: pal_shadow = 8'd20;
        5'd4: pal_shadow = 8'd26;
        5'd5: pal_shadow = 8'd32;
        5'd6: pal_shadow = 8'd39;
        5'd7: pal_shadow = 8'd45;
        5'd8: pal_shadow = 8'd52;
        5'd9: pal_shadow = 8'd58;
        5'd10: pal_shadow = 8'd64;
        5'd11: pal_shadow = 8'd71;
        5'd12: pal_shadow = 8'd77;
        5'd13: pal_shadow = 8'd84;
        5'd14: pal_shadow = 8'd90;
        5'd15: pal_shadow = 8'd97;
        5'd16: pal_shadow = 8'd103;
        5'd17: pal_shadow = 8'd110;
        5'd18: pal_shadow = 8'd116;
        5'd19: pal_shadow = 8'd123;
        5'd20: pal_shadow = 8'd129;
        5'd21: pal_shadow = 8'd136;
        5'd22: pal_shadow = 8'd142;
        5'd23: pal_shadow = 8'd149;
        5'd24: pal_shadow = 8'd155;
        5'd25: pal_shadow = 8'd161;
        5'd26: pal_shadow = 8'd168;
        5'd27: pal_shadow = 8'd174;
        5'd28: pal_shadow = 8'd181;
        5'd29: pal_shadow = 8'd187;
        5'd30: pal_shadow = 8'd193;
        5'd31: pal_shadow = 8'd200;
        default: pal_shadow = 8'd0;
    endcase
endfunction
function automatic [7:0] pal_hilight(input [4:0] v);
    case (v)
        5'd0: pal_hilight = 8'd55;
        5'd1: pal_hilight = 8'd62;
        5'd2: pal_hilight = 8'd68;
        5'd3: pal_hilight = 8'd74;
        5'd4: pal_hilight = 8'd81;
        5'd5: pal_hilight = 8'd87;
        5'd6: pal_hilight = 8'd94;
        5'd7: pal_hilight = 8'd100;
        5'd8: pal_hilight = 8'd106;
        5'd9: pal_hilight = 8'd113;
        5'd10: pal_hilight = 8'd119;
        5'd11: pal_hilight = 8'd126;
        5'd12: pal_hilight = 8'd132;
        5'd13: pal_hilight = 8'd139;
        5'd14: pal_hilight = 8'd145;
        5'd15: pal_hilight = 8'd152;
        5'd16: pal_hilight = 8'd158;
        5'd17: pal_hilight = 8'd165;
        5'd18: pal_hilight = 8'd171;
        5'd19: pal_hilight = 8'd178;
        5'd20: pal_hilight = 8'd184;
        5'd21: pal_hilight = 8'd191;
        5'd22: pal_hilight = 8'd197;
        5'd23: pal_hilight = 8'd203;
        5'd24: pal_hilight = 8'd210;
        5'd25: pal_hilight = 8'd216;
        5'd26: pal_hilight = 8'd223;
        5'd27: pal_hilight = 8'd229;
        5'd28: pal_hilight = 8'd235;
        5'd29: pal_hilight = 8'd242;
        5'd30: pal_hilight = 8'd248;
        5'd31: pal_hilight = 8'd255;
        default: pal_hilight = 8'd0;
    endcase
endfunction
