"""315-5242 colour output: 5-bit resistor ladders per channel, ported from
MAME sega_16bit_common_base::palette_init / paletteram_w and
emu/video/resnet.cpp compute_resistor_weights (single network, autoscale).

Run as a script to emit rtl/video/yb_pal_lut.svh."""
import os


def compute_resistor_weights(minval, maxval, resistances):
    n = len(resistances)
    r = [float(x) for x in resistances]
    w = []
    for i in range(n):
        R0 = 1.0 / 1e12
        R1 = 1.0 / 1e12
        for j in range(n):
            if j == i:
                if r[j] != 0.0:
                    R1 += 1.0 / r[j]
            else:
                if r[j] != 0.0:
                    R0 += 1.0 / r[j]
        R0 = 1.0 / R0
        R1 = 1.0 / R1
        vout = (maxval - minval) * R0 / (R1 + R0) + minval
        w.append(min(max(vout, float(minval)), float(maxval)))
    scale = float(maxval) / sum(w)
    return [x * scale for x in w]


def combine_weights(weights, *bits):
    return int(sum(wt * b for wt, b in zip(weights, bits)) + 0.5)


RES_NORMAL = [3900, 2000, 1000, 1000 // 2, 1000 // 4, 0]
RES_SH = [3900, 2000, 1000, 1000 // 2, 1000 // 4, 470]


def tables():
    wn = compute_resistor_weights(0, 255, RES_NORMAL)
    wsh = compute_resistor_weights(0, 255, RES_SH)
    normal, shadow, hilight = [], [], []
    for value in range(32):
        i0, i1, i2, i3, i4 = [(value >> k) & 1 for k in range(5)]
        normal.append(combine_weights(wn, i0, i1, i2, i3, i4, 0))
        shadow.append(combine_weights(wsh, i0, i1, i2, i3, i4, 0))
        hilight.append(combine_weights(wsh, i0, i1, i2, i3, i4, 1))
    return normal, shadow, hilight


def entry_rgb(word, effects=False):
    """(r, g, b) for a palette word; effects selects the shadow/hilight bank."""
    normal, shadow, hilight = tables()
    r = ((word >> 12) & 1) | ((word << 1) & 0x1e)
    g = ((word >> 13) & 1) | ((word >> 3) & 0x1e)
    b = ((word >> 14) & 1) | ((word >> 7) & 0x1e)
    if not effects:
        return normal[r], normal[g], normal[b]
    t = hilight if (word & 0x8000) else shadow
    return t[r], t[g], t[b]


if __name__ == "__main__":
    normal, shadow, hilight = tables()
    out = os.path.join(os.path.dirname(__file__), "..", "..", "rtl", "video", "yb_pal_lut.svh")
    with open(out, "w") as f:
        f.write("// Generated by verif/models/palette5242.py from MAME's resistor weights.\n")
        f.write("// 5-bit channel value -> 8-bit output: normal, shadow (effects bank,\n")
        f.write("// palette bit 15 clear) and hilight (effects bank, bit 15 set).\n")
        # case functions rather than unpacked-array parameters: Quartus 17
        # rejects untyped aggregate localparams, functions synthesise anywhere
        for name, t in (("pal_normal", normal), ("pal_shadow", shadow), ("pal_hilight", hilight)):
            f.write(f"function automatic [7:0] {name}(input [4:0] v);\n    case (v)\n")
            for i, v in enumerate(t):
                f.write(f"        5'd{i}: {name} = 8'd{v};\n")
            f.write(f"        default: {name} = 8'd0;\n    endcase\nendfunction\n")
    print("normal ", normal)
    print("shadow ", shadow)
    print("hilight", hilight)
